version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: shoppinglist
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql:/docker-entrypoint-initdb.d"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  backend:
    restart: always
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3001:3001"
    network_mode: host
