version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: shoppinglist
    ports:
      - "3306:3306"

  db-test:
    image: mysql:latest
    container_name: mysql_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: shoppinglist_test
    ports:
      - "3305:3306"

  backend:
    restart: always
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
