export type EventType =
  | "category.create"
  | "category.update"
  | "category.delete"
  | "category.deleteAll"
  | "item.create"
  | "item.update"
  | "item.updateSequences"
  | "item.delete"
  | "item.deleteAll"
  | "item.deleteChecked"
  | "standardItem.create"
  | "standardItem.update"
  | "standardItem.delete"
  | "standardItem.deleteAll";
